"""

Revision ID: 07a604f230c0
Revises: 6b9812815344
Create Date: 2026-01-09 15:11:15.520477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07a604f230c0'
down_revision = '6b9812815344'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_paid')
    op.drop_column('users', 'referral_payments_count')
    op.drop_column('users', 'payout_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payout_amount', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('referral_payments_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('referral_paid', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
