"""add_lyrics_to_music_tasks

Revision ID: 1ee579c2dfa9
Revises: f8c65f1d7b12
Create Date: 2026-01-21 14:33:09.185358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee579c2dfa9'
down_revision = 'f8c65f1d7b12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_tasks', sa.Column('lyrics', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_tasks', 'lyrics')
    # ### end Alembic commands ###
