"""

Revision ID: 68d96810d4ca
Revises: 1ca213e116d1
Create Date: 2026-01-10 21:07:48.998901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68d96810d4ca'
down_revision = '1ca213e116d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('user_idpk', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.String(length=200), nullable=False),
    sa.Column('telegram_charge_id', sa.String(length=200), nullable=True),
    sa.Column('provider_charge_id', sa.String(length=200), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_idpk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_idpk'), 'transactions', ['user_idpk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_idpk'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###