"""

Revision ID: 6961a63183aa
Revises: 68d96810d4ca
Create Date: 2026-01-10 21:50:42.946035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6961a63183aa'
down_revision = '68d96810d4ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('manager_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_transactions_manager_id'), 'transactions', ['manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_manager_id'), table_name='transactions')
    op.drop_column('transactions', 'manager_id')
    # ### end Alembic commands ###
