"""

Revision ID: 6b9812815344
Revises:
Create Date: 2026-01-09 14:50:53.366186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9812815344'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('referrer_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('payout_amount', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('referral_paid', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('referral_payments_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_payments_count')
    op.drop_column('users', 'referral_paid')
    op.drop_column('users', 'payout_amount')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'referrer_id')
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###
